# Generated by Django 3.1.3 on 2021-04-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_auto_20210416_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication_list',
            name='cost',
        ),
    ]
